### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xavroy2** [valleyofdoom/ReservedCpuSets#1]
Is it possible to make this app have only interrupts be putt off the selected cores instead of interrupts and programs. This would be the most useful for me personally and if its not possible then I fully understand. 

I do appologize for my lack of knowledge on this topic but by making my program "realtime" in task manager or registry will this make the cores selected to be "reserved" be able to be used again. Because I am seeing 0% usage while running per say a game when all I wanted was for no interrupts to be running on those cores.

**Comment by valleyofdoom** [comment]
You can simply assess what drivers are scheduling ISRs and DPCs on the core you wish to be isolated and manually move them to another core as explained [here](https://github.com/valleyofdoom/PC-Tuning#1141-kernel-mode-scheduling-interrupts-dpcs-and-more). I can't reproduce reserved cores being utilized when the process priority is real-time.
