### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ilie321** [valleyofdoom/ReservedCpuSets#2]
So this  is taken in  account at boot also?  For example if you have an faulty core on cpu and you want windows not to use it at all. Thank you

**Comment by valleyofdoom** [comment]
Yes but why do you have a faulty CPU?

**Comment by ilie321** [comment]
Is just 1 core that is not working properly and i want to skip it. Thank you

**Comment by ilie321** [comment]
It works but form 2 3 reboots 1 fails do you have any idea why is that? If windows starts then no problem but at windows boot sometimes fails because it is still accessing that core.
